---
title: "NEWS"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NEWS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# OpeNoise 0.2-13

* Add new function AcousticQuantilePlot
* Add data AcousticWeightingTable


# OpeNoise 0.2-12

* Add new colour/aspect for PlotSpectogram function
* Add na.omit in HourlyEmean function
* search.tone function modified (time indipendent)
* Correct same bugs in LdenCalculator function
* Add qualitative flag to IntrusivityIndex function
* Add new column "BWn" (letterature values) in table dfBW


# OpeNoise 0.2-11

* Add argument dataset in ExtractIndex and MarkApply function for Shiny application


# OpeNoise 0.2-10

* Add argument timeZone in HourlyEmean 


# OpeNoise 0.2-9

* Changed library name from AcousticCalc to OpeNoise
* fixed bug on search.tone function
* fixed several minor bug
* Added function searchImpulse
* Added function dfImpulsiveTransform
* Added function IntrusiveIndex


# AcousticCalc 0.2-7

* Added new functions in total there are 20 functions.
* Added 7 example dataset.
* Added documentation.
